// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SW.Mtm.Model;
using SW.Mtm.PgSql;

namespace SW.Mtm.PgSql.Migrations
{
    [DbContext(typeof(MtmDbContext))]
    [Migration("20201204102740_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mtm")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:Sequence:.EntityFrameworkHiLoSequence", "'EntityFrameworkHiLoSequence', '', '1', '10', '', '', 'Int64', 'False'");

            modelBuilder.Entity("SW.Mtm.Domain.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnName("deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("DeletedBy")
                        .HasColumnName("deleted_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnName("deleted_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Disabled")
                        .HasColumnName("disabled")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnName("display_name")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<byte>("EmailProvider")
                        .HasColumnName("email_provider")
                        .HasColumnType("smallint");

                    b.Property<bool>("EmailVerified")
                        .HasColumnName("email_verified")
                        .HasColumnType("boolean");

                    b.Property<bool>("Landlord")
                        .HasColumnName("landlord")
                        .HasColumnType("boolean");

                    b.Property<byte>("LoginMethods")
                        .HasColumnName("login_methods")
                        .HasColumnType("smallint");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnName("modified_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<bool>("PhoneVerified")
                        .HasColumnName("phone_verified")
                        .HasColumnType("boolean");

                    b.Property<IEnumerable<ProfileDataItem>>("ProfileData")
                        .HasColumnName("profile_data")
                        .HasColumnType("jsonb");

                    b.Property<string[]>("Roles")
                        .HasColumnName("roles")
                        .HasColumnType("text[]")
                        .HasMaxLength(100);

                    b.Property<string>("SecondFactorKey")
                        .HasColumnName("second_factor_key")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<byte>("SecondFactorMethod")
                        .HasColumnName("second_factor_method")
                        .HasColumnType("smallint");

                    b.Property<int?>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("ix_account_email");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasName("ix_account_phone");

                    b.HasIndex("TenantId")
                        .HasName("ix_account_tenant_id");

                    b.ToTable("account","mtm");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Disabled = false,
                            DisplayName = "System",
                            EmailProvider = (byte)0,
                            EmailVerified = false,
                            Landlord = false,
                            LoginMethods = (byte)1,
                            PhoneVerified = false,
                            Roles = new[] { "Mtm.Accounts.Create", "Mtm.Accounts.ResetPassword", "Mtm.Accounts.InitiatePasswordReset" },
                            SecondFactorMethod = (byte)0
                        },
                        new
                        {
                            Id = "2",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Disabled = false,
                            DisplayName = "Admin",
                            Email = "admin@xyz.com",
                            EmailProvider = (byte)0,
                            EmailVerified = true,
                            Landlord = true,
                            LoginMethods = (byte)2,
                            Password = "$SWHASH$V1$10000$VQCi48eitH4Ml5juvBMOFZrMdQwBbhuIQVXe6RR7qJdDF2bJ",
                            PhoneVerified = true,
                            Roles = new[] { "Mtm.Accounts.Create" },
                            SecondFactorMethod = (byte)0
                        },
                        new
                        {
                            Id = "2d3d997abdaf4e2880f2b4737aab6b0d",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Disabled = false,
                            DisplayName = "Sample User",
                            Email = "sample@xyz.com",
                            EmailProvider = (byte)0,
                            EmailVerified = true,
                            Landlord = false,
                            LoginMethods = (byte)2,
                            Password = "$SWHASH$V1$10000$VQCi48eitH4Ml5juvBMOFZrMdQwBbhuIQVXe6RR7qJdDF2bJ",
                            PhoneVerified = false,
                            SecondFactorMethod = (byte)0
                        },
                        new
                        {
                            Id = "4a64f3640d914cfa98f3c166fe22f59a",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Disabled = false,
                            DisplayName = "Sample User MFA",
                            Email = "samplewithmfa@xyz.com",
                            EmailProvider = (byte)0,
                            EmailVerified = true,
                            Landlord = false,
                            LoginMethods = (byte)2,
                            Password = "$SWHASH$V1$10000$VQCi48eitH4Ml5juvBMOFZrMdQwBbhuIQVXe6RR7qJdDF2bJ",
                            PhoneVerified = false,
                            SecondFactorMethod = (byte)1
                        },
                        new
                        {
                            Id = "40ec4db42e434bf5a17f2065521a5219",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Disabled = false,
                            DisplayName = "Sample User Phone",
                            EmailProvider = (byte)0,
                            EmailVerified = false,
                            Landlord = false,
                            LoginMethods = (byte)4,
                            Phone = "12345678",
                            PhoneVerified = true,
                            SecondFactorMethod = (byte)0
                        },
                        new
                        {
                            Id = "4cc3320b49af45dfb7ec13b072701acc",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Disabled = false,
                            DisplayName = "Sample User API",
                            EmailProvider = (byte)0,
                            EmailVerified = false,
                            Landlord = false,
                            LoginMethods = (byte)1,
                            PhoneVerified = false,
                            SecondFactorMethod = (byte)0
                        });
                });

            modelBuilder.Entity("SW.Mtm.Domain.Invitation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("AccountId")
                        .HasColumnName("account_id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnName("deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("DeletedBy")
                        .HasColumnName("deleted_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnName("deleted_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnName("modified_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_invitation");

                    b.HasIndex("TenantId")
                        .HasName("ix_invitation_tenant_id");

                    b.HasIndex("AccountId", "TenantId")
                        .IsUnique()
                        .HasName("ix_invitation_account_id_tenant_id");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique()
                        .HasName("ix_invitation_email_tenant_id");

                    b.HasIndex("Phone", "TenantId")
                        .IsUnique()
                        .HasName("ix_invitation_phone_tenant_id");

                    b.ToTable("invitation","mtm");
                });

            modelBuilder.Entity("SW.Mtm.Domain.OtpToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("AccountId")
                        .HasColumnName("account_id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("LoginMethod")
                        .HasColumnName("login_method")
                        .HasColumnType("smallint");

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<byte>("Type")
                        .HasColumnName("type")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("pk_otp_token");

                    b.HasIndex("AccountId")
                        .HasName("ix_otp_token_account_id");

                    b.ToTable("otp_token","mtm");
                });

            modelBuilder.Entity("SW.Mtm.Domain.PasswordResetToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("AccountId")
                        .HasColumnName("account_id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_token");

                    b.HasIndex("AccountId")
                        .HasName("ix_password_reset_token_account_id");

                    b.ToTable("password_reset_token","mtm");
                });

            modelBuilder.Entity("SW.Mtm.Domain.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("AccountId")
                        .HasColumnName("account_id")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte>("LoginMethod")
                        .HasColumnName("login_method")
                        .HasColumnType("smallint");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("AccountId")
                        .HasName("ix_refresh_token_account_id");

                    b.ToTable("refresh_token","mtm");
                });

            modelBuilder.Entity("SW.Mtm.Domain.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "EntityFrameworkHiLoSequence")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("created_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnName("deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("DeletedBy")
                        .HasColumnName("deleted_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnName("deleted_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnName("display_name")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("character varying(100)")
                        .IsFixedLength(false)
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnName("modified_on")
                        .HasColumnType("timestamp without time zone");

                    b.Property<IEnumerable<ProfileDataItem>>("ProfileData")
                        .HasColumnName("profile_data")
                        .HasColumnType("jsonb");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant","mtm");
                });

            modelBuilder.Entity("SW.Mtm.Domain.Account", b =>
                {
                    b.HasOne("SW.Mtm.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_account_tenant_tenant_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("SW.Mtm.Domain.ApiCredential", "ApiCredentials", b1 =>
                        {
                            b1.Property<string>("AccountId")
                                .HasColumnName("account_id")
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("id")
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnName("key")
                                .HasColumnType("character varying(500)")
                                .HasMaxLength(500)
                                .IsUnicode(false);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnName("name")
                                .HasColumnType("character varying(500)")
                                .HasMaxLength(500);

                            b1.HasKey("AccountId", "Id")
                                .HasName("pk_api_credential");

                            b1.HasIndex("Key")
                                .IsUnique()
                                .HasName("ix_account_api_credential_key");

                            b1.ToTable("account_api_credential","mtm");

                            b1.WithOwner()
                                .HasForeignKey("AccountId")
                                .HasConstraintName("fk_api_credential_account_account_id");

                            b1.HasData(
                                new
                                {
                                    AccountId = "1",
                                    Id = 1,
                                    Key = "dcc8edf250b04c94a31eb161fea11b5b",
                                    Name = "default"
                                },
                                new
                                {
                                    AccountId = "4cc3320b49af45dfb7ec13b072701acc",
                                    Id = 2,
                                    Key = "7facc758283844b49cc4ffd26a75b1de",
                                    Name = "default"
                                });
                        });

                    b.OwnsMany("SW.Mtm.Domain.TenantMembership", "TenantMemberships", b1 =>
                        {
                            b1.Property<string>("AccountId")
                                .HasColumnName("account_id")
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("id")
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<IEnumerable<ProfileDataItem>>("ProfileData")
                                .HasColumnName("profile_data")
                                .HasColumnType("jsonb");

                            b1.Property<int>("TenantId")
                                .HasColumnName("tenant_id")
                                .HasColumnType("integer");

                            b1.Property<byte>("Type")
                                .HasColumnName("type")
                                .HasColumnType("smallint");

                            b1.HasKey("AccountId", "Id")
                                .HasName("pk_tenant_membership");

                            b1.HasIndex("TenantId")
                                .HasName("ix_account_tenant_membership_tenant_id");

                            b1.ToTable("account_tenant_membership","mtm");

                            b1.WithOwner()
                                .HasForeignKey("AccountId")
                                .HasConstraintName("fk_tenant_membership_account_account_id");

                            b1.HasOne("SW.Mtm.Domain.Tenant", null)
                                .WithMany()
                                .HasForeignKey("TenantId")
                                .HasConstraintName("fk_account_tenant_membership_tenant_tenant_id")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
                });

            modelBuilder.Entity("SW.Mtm.Domain.Invitation", b =>
                {
                    b.HasOne("SW.Mtm.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_invitation_account_account_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SW.Mtm.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_invitation_tenant_tenant_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SW.Mtm.Domain.OtpToken", b =>
                {
                    b.HasOne("SW.Mtm.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_otp_token_account_account_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SW.Mtm.Domain.PasswordResetToken", b =>
                {
                    b.HasOne("SW.Mtm.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_password_reset_token_account_account_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SW.Mtm.Domain.RefreshToken", b =>
                {
                    b.HasOne("SW.Mtm.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .HasConstraintName("fk_refresh_token_account_account_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
