<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SW.Mtm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="10.3.6" />
    <PackageReference Include="Otp.NET" Version="1.2.2" />
    <PackageReference Include="SimplyWorks.EfCoreExtensions" Version="8.1.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SW.Mtm.Sdk\SW.Mtm.Sdk.csproj" />
  </ItemGroup>

</Project>
